services:
  web:
    build: .
    env_file: .env
    restart: always
    depends_on:
      - db
    ports:
      - 7777:80
    environment:
      DATABASE_URL: postgres://hello_django:hello_django@db:5432/hello_django_dev
      REDIS_URL: redis://redis:6379/0
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_DOMAIN_NAME: ${R2_DOMAIN_NAME}
      R2_ENDPOINT_URL: ${R2_ENDPOINT_URL}
      R2_SUBFOLDER: ${R2_SUBFOLDER}
      R2_KEY: ${R2_KEY}
      R2_SECRET: ${R2_SECRET}
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
